'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MatchTeams
    Public Property Team_id As Integer
    Public Property Match_id As Integer
    Public Property TeamId1Points As Nullable(Of Integer)
    Public Property TeamId2Points As Nullable(Of Integer)
    Public Property TeamId1DraftURL As String
    Public Property TeamId2DraftURL As String
    Public Property TeamId1CaptainUserId As Nullable(Of Integer)
    Public Property TeamId2CaptainUserId As Nullable(Of Integer)

    Public Overridable Property Match As Match
    Public Overridable Property Team As Team

End Class
