'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class ksBotSQL2Entities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=ksBotSQL2Entities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Match() As DbSet(Of Match)
    Public Overridable Property MatchTeams() As DbSet(Of MatchTeams)
    Public Overridable Property Param() As DbSet(Of Param)
    Public Overridable Property Scoreboard() As DbSet(Of Scoreboard)
    Public Overridable Property sysdiagrams() As DbSet(Of sysdiagrams)
    Public Overridable Property Team() As DbSet(Of Team)
    Public Overridable Property User() As DbSet(Of User)

End Class
