'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class User
    Public Property id As Integer
    Public Property discord_id As String
    Public Property Username As String
    Public Property BtagId As String
    Public Property Division As String
    Public Property CurrentSR As Nullable(Of Integer)
    Public Property APICurrentSR As Nullable(Of Integer)
    Public Property APIHero1 As String
    Public Property APIHero2 As String
    Public Property APIHero3 As String
    Public Property APIKillAvg As Nullable(Of Double)
    Public Property APIDeathAvg As Nullable(Of Double)
    Public Property APIHealAvg As Nullable(Of Double)
    Public Property Team_id As Nullable(Of Integer)
    Public Property added As Nullable(Of Date)
    Public Property attending As Nullable(Of Integer)
    Public Property APITimePlayed As Nullable(Of Double)
    Public Property APIAvatarURL As String
    Public Property APIWinRate As Nullable(Of Double)

    Public Overridable Property Team As Team
    Public Overridable Property Match As ICollection(Of Match) = New HashSet(Of Match)
    Public Overridable Property Team1 As ICollection(Of Team) = New HashSet(Of Team)

End Class
